import { describe, expect, test } from "vitest";
import { day08 } from "./solution";

const testInput = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;

describe("December 08", () => {
  test("silver - test input", () => {
    expect(day08.silver(testInput)).toBe(14);
  });

  test("silver - actual puzzle input", async () => {
    expect(day08.silver(await day08.readInput())).toBe(392);
  });

  test("gold - test input", () => {
    expect(day08.gold(testInput)).toBe(34);
  });

  test("gold - actual puzzle input", async () => {
    expect(day08.gold(await day08.readInput())).toBe(1235);
  });
});
