import { describe, expect, test } from "bun:test";
import { day07 } from "./solution";

const testInput = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;

describe("December 07", () => {
  test("silver - test input", () => {
    expect(day07.silver(testInput)).toBe(21);
  });

  test("silver - actual puzzle input", async () => {
    expect(day07.silver(await day07.readInput())).toBe(1581);
  });

  test("gold - test input", () => {
    expect(day07.gold(testInput)).toBe(40);
  });

  test("gold - actual puzzle input", async () => {
    expect(day07.gold(await day07.readInput())).toBe(73007003089792);
  });
});
